"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ICCU_MAG_METADATA.py']
DATA_FILES = ['handle_upload.py']
OPTIONS = {}
install_requires=[
    'lxml',
    'filetype>=1.0.8',
    'requests',
    'tkinter',
    'Pillow',
    'exiftool'
]
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
